### ISSUE TITLE
坦白说加密方式更新啦！一起来破解一下？

### ISSUE THREAD

**Issue by CoreJa** [KB5201314/ConfessTalkKiller#2]
希望有空的小伙伴能拿小号测试一下，把明文和对应密文发出来，一起找找加密方式

**Comment by imlk0** [comment]
近期没什么时间啊，看源码估计能找到线索，但是我最近得复习考试

**Comment by CoreJa** [comment]
巧了我也在赶考，看源码是啥意思？逆向工程不太会…

**Comment by imlk0** [comment]
就是逆向看扣扣的源码，然后分析解密流程

**Comment by CoreJa** [comment]
@KB5201314 大佬逆向麻烦不？能不能指个路？我代码还是会看的

**Comment by Polaris233** [comment]
加密方式变更之前已经探明的发送人还是能看到的，变更之后的全部Unknown。

**Comment by CoreJa** [comment]
提供一个
<pre>*S1*oKvPoK6kow6zNeczNK6ANec5</pre>
944822354

**Comment by imlk0** [comment]
jadx
@Core00077
开QQ的dex

**Comment by sudami** [comment]
QQ 7.5.6 得重新适配啦，博主加油O(∩_∩)O~

**Comment by imlk0** [comment]
@Core00077 
*S1*oKvPoK6kow6zNeczNK6ANec5
这个是哪里来的，是新的吗，我看最新的获取到的qq号全是14411521开头的，怕不是开始计数了吧
```
144115210965149227
144115210882581770
144115210876459339
144115210876723659
144115210958067047
144115210877560478
144115210958293201

```

**Comment by WankkoRee** [comment]
感觉是现在的加密戳是在服务器进行匿名中转了，挺难搞

**Comment by WankkoRee** [comment]
不过好像同一个人发的是同一个加密戳，可能可以逆向

**Comment by WankkoRee** [comment]
2383456183：144115210888794758
2394563024：144115210969077026
1832571300：144115210969106771
3501515464：144115210969131267
3140218920：144115210969145159

**Comment by wangweifeng1121** [comment]
144115210875754701

**Comment by wangweifeng1121** [comment]
这怎么破

**Comment by imlk0** [comment]
@dreamunicorn 
同一个人发的是同一个加密戳是什么意思
这个加密戳是指什么

**Comment by imlk0** [comment]
这些144115210xxxxxxxx感觉是坦白说的序号，给所有从昨天（2018年6月7号）开始的坦白说都排了个序号，然后在
com.tencent.mobileqq.activity.aio.rebuild.ConfessChatPie (classes6.dex)里面我找到了一个方法，似乎是一个加密函数
```
    public static String a(String str, String str2) {
        try {
            Object bytes = str.getBytes("utf-8");
            int length = bytes.length;
            if (length % 16 != 0) {
                length += 16 - (length % 16);
            }
            Object obj = new byte[length];
            System.arraycopy(bytes, 0, obj, 0, bytes.length);
            Cipher instance = Cipher.getInstance("AES/ECB/NoPadding");
            Key secretKeySpec = new SecretKeySpec(str2.getBytes(), "AES");
            byte[] bArr = new byte[16];
            for (int i = 0; i < 16; i++) {
                bArr[i] = (byte) 0;
            }
            instance.init(1, secretKeySpec);
            return Utils.a(instance.doFinal(obj));
        } catch (Exception e) {
            e.printStackTrace();
            QLog.e("Q.aio.ConfessChatPie", 1, "encryptEvilUin error: " + e.getMessage());
            return null;
        }
    }
```
这个方法只有两个地方被调用到
![default](https://user-images.githubusercontent.com/14936301/41168460-9cf6bfde-6b78-11e8-953f-787630e5de23.png)
其中一个是
![default](https://user-images.githubusercontent.com/14936301/41168561-f1d3d9ba-6b78-11e8-89a8-a452bd445c70.png)

在“举报按钮的监听onClick方法中”
而且第一个参数是那个`144115210xxxxxxxxxxxx`二个参数始终是`6bW#X@~L.+X)4%$>`，
这是一次函数调用的返回值：
![default](https://user-images.githubusercontent.com/14936301/41168996-25c79aa8-6b7a-11e8-8bf0-4e159922756c.png)

这个加密函数返回的值，被用于向服务器发送请求时唯一标记这个坦白说，下面是一位老哥抓到一次和这条坦白说相关的请求的的内容，注意其中的`uin`
![default](https://user-images.githubusercontent.com/14936301/41168735-746ea7ba-6b79-11e8-9764-65bb9696f882.png)

所以，从这里看来，似乎将坦白说和对方QQ号的联系都放到服务器端了，本地应该是没有下发QQ号了。

感觉要搞出对应的QQ号，除非是哪里还有逻辑上的漏洞吧。

**Comment by wangrwang123** [comment]
144115210969142116大家帮一下，谢谢

**Comment by gaodatang** [comment]
144115210889874989
144115210885545068

跪求大神帮忙破一下有急用

**Comment by WankkoRee** [comment]
@KB5201314  加密戳就是指144115那一串，同一个QQ号是对应同一个加密戳的

**Comment by imlk0** [comment]
我一开始猜测那个144115是序号，是否是同一个人还得验证看看

**Comment by WankkoRee** [comment]
@KB5201314 我这边拿5个小号试过了，每个号一直都是同一个加密戳，刚才试了一下和昨晚还是一样的，应该不受时间影响，而且对多个号发送也是用的同一个加密戳。
`2383456183：144115210888794758
2394563024：144115210969077026
1832571300：144115210969106771
3501515464：144115210969131267
3140218920：144115210969145159`

**Comment by gaodatang** [comment]
帮我看看吧

**Comment by imlk0** [comment]
@dreamunicorn 惊了，我也来一下试试。
另外，有什么办法获取到接收方的加密戳吗

**Comment by WankkoRee** [comment]
@KB5201314 我这边抓包抓到接收方的uin还是本身的QQ号
![default](https://user-images.githubusercontent.com/21287731/41186085-ac581294-6bc2-11e8-8188-65d3b0c9ae72.png)
最后一个toUin就是我自己的QQ（接收方）

**Comment by WankkoRee** [comment]
@KB5201314 从这个json变量名的命名来看，Encode暗示着应该是有decode的方法的

**Comment by WankkoRee** [comment]
感觉我们这个144115可能是被误导的解密结果，试试从现在原始的*S1*oKvPoK6kow6zN***********数据入手

**Comment by imlk0** [comment]
这个*s1*oK啥啥啥的还和之前的一样长吗

**Comment by governormars** [comment]
加密方式变了，那个加密戳没有意义的。不一样长了。

**Comment by WankkoRee** [comment]
长出前一段东西，也就是解出来的144115210

**Comment by governormars** [comment]
多出oKvPoK6kow6z

**Comment by imlk0** [comment]
这就很麻烦了。。。。既然这样的话后面那些也不是QQ号吧

**Comment by governormars** [comment]
估计只是个序列，云端存储对应QQ。我觉得无法解密了。

**Comment by imlk0** [comment]
我也觉得，不过有人发现举报那里可以看，就是先去举报人家一波，然后去QQ安全中心可以看自己举报过的人，然后就看到QQ号了

**Comment by governormars** [comment]
233这也太秀了

**Comment by qq9077** [comment]
@KB5201314
从你提供的 ConfessChatPie.a()中可以看到
str和 str2被这样用到了
 Key secretKeySpec = new SecretKeySpec(str2.getBytes(), "AES");
instance.init(1, secretKeySpec);
str被复制到了obj
return Utils.a(instance.doFinal(obj));
我写加密算法的习惯就是  instance.init初始化参数
instance.doFinal就是加密结果
应该从 这个Utils.a()获取的参数入手看下是不是加密结果
如果是的话 就需要单独把这个 instance 的加密算法 对现有的 加密算法进行对比
找到加密方式 然后找到 加密需要的参数 
然后套用通用的加密算法 使用他的参数 是否能计算出结果
我就喜欢在原有加密算法稍作修改 以防止被串门

**Comment by imlk0** [comment]
@9077，但是问题是这里`ConfessChatPie.a()`似乎没有具体的QQ号被传进去，传进去的是144115210xxxxxx，感觉不是很可行，这里加密只是为了发给服务器

**Comment by imlk0** [comment]
@Core00077 @dreamunicorn @qq9077 @governormars 
感觉现在的办法只有，看看怎么样才能获取到全部的QQ好友对应的`confessorUin`，然后逐个遍历，但是这个东西要去哪里找呢

**Comment by governormars** [comment]
这个东西我觉得写个自动举报方法就ok，一般一个小时后安全中心就能看到对应qq（举报不成功）。然后抓取对应qq就行。

**Comment by WankkoRee** [comment]
举报不行...我早上举报了一下，然后举报成功了？？？上面说写个自动举报的，你想要让好友拿刀砍你三条街吗

**Comment by governormars** [comment]
举报实测可以，原因填写其他。只要不是骂人的都举报不成功的。

**Comment by WankkoRee** [comment]
emm...我就是填的其他，然后就...成功了，而且也不显示QQ号啊
![default](https://user-images.githubusercontent.com/21287731/41187380-43f1c2aa-6bda-11e8-86ca-059ced1f3ecf.png)

**Comment by imlk0** [comment]
@dreamunicorn 去QQ安全中心，看举报过的人

**Comment by WankkoRee** [comment]
好的看见了，确实有QQ，不过举报成功是真的烦

**Comment by imlk0** [comment]
![default](https://user-images.githubusercontent.com/14936301/41187428-7bf82e54-6bdb-11e8-86d1-13fe3b6c0738.png)

@dreamunicorn 不过好像也被和谐了，这是真的尴尬

**Comment by qq9077** [comment]
@KB5201314 目前在平台有任何地方可以显示真实QQ号码的地方吗 如果有 那必然有个转换关系在这里，否则可能全程对客户端匿名

**Comment by WankkoRee** [comment]
@qq9077 安全中心显示的是真实QQ

**Comment by imlk0** [comment]
@qq9077 QQ安全中心里出现的那个应该是服务端的业务逻辑漏洞，没考虑全导致的，和移动端应该没有关系

**Comment by imlk0** [comment]
刚刚试了查看好友的坦白说，返回的是这种
```
{"topicId":10561,
"confess":"大众点评专家",
"confessorNick":"一个梅州的男生",
"confessorUin":"*S1*oKvPoK6kow6zNecq7K4lNK45",
"confessorSex":0,
"confessTime":1528471875,
"nick_name":"咸鱼。",
"toUin":"*S1*NenqNKElowEi",
"bg_type":1,
"chatType":0,
"callback":"__MQQ_CALLBACK_AUTO_30"}
```
这里没有下发我那个好友的`confessorUin`，只有他的QQ号

还抓了发送坦白说时的请求：
传过去的toUin是接收者QQ号，没有看到接收者的`confessorUin`。

看起来，这两个地方都没法突破

**Comment by qq9077** [comment]
坦白说 可能只保存了 这条信息的 内容 以及发起者的 外键， 而参与者也不是直接连接到 QQ帐号信息主表，按照较为规范的流程也是应该创建一个业务表（用户信息主表）指向 QQ帐号， 这个表会记录 这个QQ号码参与坦白说这个业务详细情况，比如什么时候参与的，避免对QQ帐号主表的频繁读取。 也是对这个业务下架的时候方面操作（删表即可）。那么你们看到的那个 144115210888794758 估计会是 这个业务表的主键，主键唯一，方便检索，根据你们发的内容应该是按时间来递增的。这样就可以做到发到客户端的时候不需要任何任何QQ信息即可。
至于安全中心应该也是一样的，定义一个新的举报类型ID，然后只要是这个ID就会把被举报人的信息指向坦白说的用户信息主表，通过这个表可以查到原始的QQ号码。举报和发坦白说不是同一个业务，呈现的数据肯定是不一样的。既是如此，那么有极大的可能性就是必须创建了举报业务才能通过查询举报的接口获取到原始的QQ号码。
目前我猜测他们应该是这样做的，因为我也会这样做。
如果是这样那就只能使用bapass漏洞，比如某个可以查询获取所有数据的CGI获取JSON，这个应该要对接口进行挖掘了。

**Comment by qq9077** [comment]
上文中 bapass 应为 bypass

**Comment by qq9077** [comment]
还有个最社会的方法  彩虹表  就是收集大量采购匹配。

**Comment by imlk0** [comment]
@qq9077
老哥您太熟练了

**Comment by sudami** [comment]
意思是完蛋啦？？？

**Comment by imlk0** [comment]
@sudami
目前没有办法

**Comment by lanlianhua99** [comment]
破解头像和昵称是不是更容易。有的软件虽然破解不了加密的QQ号，但是能显示昵称和头像。

**Comment by qq9077** [comment]
都是自己的数据应该可以用，方法就是获取到昵称后与自己的QQ好友进行匹配。单向好友可能会匹配不出来，还有.....IDQQ里的业务好像下线了...

**Comment by lanlianhua99** [comment]
我不是程序员，我只是吃瓜群众，刚刚想起的点子

**Comment by imlk0** [comment]
@lanlianhua99@qq9077

你的意思是能用这个144115查出头像？

**Comment by lanlianhua99** [comment]
不是

**Comment by lanlianhua99** [comment]
我只是觉得显示头像比显示正确的QQ号更容易

**Comment by WankkoRee** [comment]
理论来说显示头像更麻烦...

**Comment by WankkoRee** [comment]
还有，你说的那个软件名称或者包名发一下呗

**Comment by lanlianhua99** [comment]
那个我前天刚注册的，还不太会用gihub。我不会发文件。你教教我或者加我QQ2082765261

**Comment by chinkeikin** [comment]
@dreamunicorn 可以看到头像的是这个项目https://github.com/Xchuanshuo/TBS

**Comment by ihewro** [comment]
@917960559  这个没什么用的，他也是通过QQ号获取到头像的

**Comment by ameaninglessname** [comment]
加油(ง •̀_•́)ง大佬们

**Comment by HHDErHuli** [comment]
*S1*oKvPoK6kow6zNK6k7ivk7i-q
815825455

*S1*oKvPoK6kow6zNK6sowEz7ici
1260933581

**Comment by meanwhilehh** [comment]
看过题主逆向的源码的图片，是题主解决了混淆的问题还是那部分源码没有混淆，如果有什么解决源码混淆的方法能推荐下吗

**Comment by WankkoRee** [comment]
@meanwhilehh QQ的代码本来就只是用了命名混淆这一种吧？图里可以看出部分变量名和函数名还是被混淆了的

**Comment by imlk0** [comment]
有一些变量名没有混淆，估计是为了收集错误信息以后好查是哪里出错了。
但是你看大部分也被混淆的不成样子了@meanwhilehh
反混淆倒是有的，jadx就有，但效果怎么说呢，对公用的SDK应该是比较管用的，能识别出一些被混淆了的SDK，但整体上来说感觉不是很好用，还是要自己慢慢调试推断更好

**Comment by oocococo** [comment]
我用同学的号测试了一下，发现IOS和安卓发送坦白说后前面的加密方式有区别
oKvPoK6kow65oe6soe-qoevz
IOS：934081345
oKvPoK6kow6zNK-kow-q7wCl
安卓：2363265999

**Comment by imlk0** [comment]
？啥不一样啊，这是不同的两个QQ号吧，当然不一样了解出来的是14411521xxxxx，和这两个QQ号在数字上没有联系

**Comment by oocococo** [comment]
上面有发
S1oKvPoK6kow6zNK6k7ivk7i-q
815825455
S1oKvPoK6kow6zNK6sowEz7ici
1260933581
一直到＊NK都是一样的，但是用苹果就很少一样的

**Comment by imlk0** [comment]
不是很清楚这个，但是QQ号和这串解出来的数字真的没有太多联系了，估计就是在服务器上面有一张表，一一对应，但是我们是没法查的

**Comment by oocococo** [comment]
既然是手机客户端解析出来QQ号想必应该有一定规律把

**Comment by imlk0** [comment]
举个例子，
从你的校园卡卡号里能直接看出你的身份证号吗

**Comment by imlk0** [comment]
手机端并没有获取到对方的QQ号

**Comment by MYLF** [comment]
小白路过，你们一群大佬在这做战术讨论，我只能在这静静的看着，祝你能讨伐成功😂

**Comment by u21h2** [comment]
等大佬们分享

**Comment by Encaik** [comment]
最近真的是不堪其扰，有个人天天给我发十几条坦白说。
我刚才才把坦白说关了，所以考虑把这个人揪出来。
在这里坐等大佬们的分析结果。

**Comment by governormars** [comment]
把issue关了吧。没意义了。

**Comment by qq9077** [comment]
@KB5201314 @Core00077 如果 我说的是如果 
在下面的数据中
{"topicId":10561,
"confess":"大众点评专家",
"confessorNick":"一个梅州的男生",
"confessorUin":"*S1*oKvPoK6kow6zNecq7K4lNK45",
"confessorSex":0,
"confessTime":1528471875,
"nick_name":"咸鱼。",
"toUin":"*S1*NenqNKElowEi",
"bg_type":1,
"chatType":0,
"callback":"__MQQ_CALLBACK_AUTO_30"}
咸鱼是发送坦白说的 人的昵称的话 
可以从 qqshow_user_friendgroup?vip=1&omode=3&g_tk={skey}&t={_t} 获取自己的所有用户的QQ号码和昵称进行匹配
如果是能获得头像信息的话 还可以通过g?b=qq&nk={qqnum}&s={pic_width} 获取的进行匹配
id.qq的业务下线了  确实令人惋惜

**Comment by qq9077** [comment]
qqshow_usersend_hotfriend?g_tk={skey}&omode=3&t={_t} 是我试用软件上的
完整版的应为  qqshow_usersend_hotfriend?g_tk={skey}&vip=1&omode=3&t={_t}

**Comment by imlk0** [comment]
@qq9077
这个截取的是"看好友收到的坦白说"
这条坦白说是好友收到的
confessorid是这条坦白说的发送者id，是144115xxxx
nick_name是那个好友的昵称
toUin是好友的QQ号

**Comment by 1997xy** [comment]
@KB5201314 试了几个朋友的号貌似发现oKvPoK6kow65是iso系统
oKvPoK6kow6z是Android系统？

**Comment by 1647561692** [comment]
大佬们加油！

**Comment by boynextdoorhth** [comment]
萌新只能说大佬加油了

**Comment by 1749107291** [comment]
144115210963964798 谢谢大佬  急求破解 加油！！！ヾ(◍°∇°◍)ﾉﾞ

**Comment by imlk0** [comment]
请不要将issue当作聊天室！

**Comment by Frozenheart1998** [comment]
问下题主 你们用的什么tool抓的包

**Comment by ae6623** [comment]
一眼就看出来，这些是唯一生成ID，18位数据库主键，解密个XX啊，每个QQ号他找了个表，做了映射，没准按照User进行了分库分表。

```
2383456183：144115210888794758
2394563024：144115210969077026
1832571300：144115210969106771
3501515464：144115210969131267
3140218920：144115210969145159
``

**Comment by GenBill** [comment]
既然无法从加密上入手，那么直接抓自己好友的数据进行筛选就好了啊。
19岁的男生，列一个表；金牛座，列一个表；认识n年，列一个表；
把这种数值挖出来，剩下的工作就纯粹是推理了。
如果有人多次选你，基本上可以直接锁定。

**Comment by Aries000004** [comment]
*S1*oKvPoK6kow6zNeczNK6ANec5 
这个结果能不能自己加密算出来，获取所有qq好友建一个字典，然后对比

**Comment by GenBill** [comment]
我觉得不行，上面已经讨论过了，一一对应关系很可能是储存在云端，即并不存在可解析表示的函数，而仅仅是用户对应表。

Aries000004 <notifications@github.com> 於 2018年6月28日 週四 上午9:20寫道：

**Comment by gxh27954** [comment]
现在有人做了软件出来，就是把加密的字符串进行解密为原QQ号

**Comment by hooooooot** [comment]
@gxh27954  那个软件在哪里 可否发一份？

**Comment by clansty** [comment]
都是大佬
我也只是想挖一个人出来
加油

**Comment by Hys12138** [comment]
oKvPoK6kow65oevP7e-P7eCq 密文
144115211044424469 用网上的码表转换
10000000000000000000000101010(前边的都相同)11001000010001000101100010101 将上面的数字十进制转换成二进制 
发现前29位都是相同的 QQ号就藏在后边不一样的二进制数中

**Comment by Hys12138** [comment]
后29位与QQ号没有线性关系😔

**Comment by lanlianhua99** [comment]
CSDN上早就破解了，码云上貌似也有。
日期7:06
链接：
https://blog.csdn.net/qq_41485414/article/details/80938490

**Comment by lanlianhua99** [comment]
CSDN上好多
https://blog.csdn.net/qq_41664447/article/details/80788100

**Comment by lanlianhua99** [comment]
最新的
8.1

**Comment by EddardStarko** [comment]
@lanlianhua99 还是没有实际的，实时获取的方案啊

**Comment by lanlianhua99** [comment]
我发的第一个不行吗

**Comment by EddardStarko** [comment]
不行，那个通过Chrome浏览器的不行。通过空间访问那个可行。但是 还是 并不是“破解”了呀。

**Comment by lanlianhua99** [comment]
大哥，csdn上最近的也挺多的，你不会自己看看吗

**Comment by Halfason** [comment]
@KB5201314    我说下我的思路。
（1）首先，坦白说现在的密文也就是*S1*ok字符串肯定是没问题的，解密后会得到144115开头的字符串
（2）这个144115字符串，在匿名、陌生人、打招呼、点赞都有应用，都是144115开头的字符串。
        我已经研究也证明了存在 官方加解密*S1*ok字符串的接口 以及官方加密144115开头字符串的接口。
          以及验证144115开头字符串是否为真实QQ号的接口，经查询，坦白说里面的144115开头字符串是不能返回正确数据的（也就是类似于QQ里面本没有激活该QQ号），但是用非坦白说的144115开头能返回正确数据（即使是空，格式也正确）
（3）我本来以为我已经破解成功了，结果坦白说的144115开头字符串和帐号本身的144115开头字符串不对应！ 也就是QQ号在传递数据给坦白说的加密过程中类似加了盐或者多重加密了啥的（或者是直接对QQ号做了更改），才导致坦白说的144115数据与本来的数据不一致（我测试对比了多组数据，也没找到思路，不是简单的加减）。但是敢肯定TX是有将QQ号加密为144115开头字符串这个算法的，而不应该是简单的映射表。（每个能被找到的QQ都能算出144115开头的数据）
（4）关键就在于一次加密时得到的这个144115开头的数据是经过再加密的，蓝瘦，如果通过逆向的时候能找到它就再好不过了。

**Comment by imlk0** [comment]
QQ在其他地方（除了坦白说）还有用到144115？？？@yc14219

**Comment by Halfason** [comment]
@KB5201314     不是都说了，QQ上关于匿名状态的 举报的时候都能看到144115字符串，也就是QQ上存在两种加密方式 一种是 星号S1星号 开头的 一种就是144115开头的

**Comment by Halfason** [comment]
楼主，我突然想到，既然你抓得到那个举报时候的函数，那能否直接提交tinyid到举报页面，而不是加密后的字符串提交(都有个密码)，或许这样举报的话系统识别不是坦白说，返回举报结果的时候就直接出来首尾数字了呢。

    楼主你要不要试一试呢，能给我加密的函数(或者tinyid也就是144115开头的)，和末尾密钥的加密函数的话，我们可以试一试

Post数据：
链接：
https://jubao.qq.com/uniform_impeach/impeach_entry
数据：
system=android&version=7.7.0&uintype=1&eviluin=(tinyid或者加密fromEncodeuin)&appname=KQQ&appid=2400002&subapp=c2c_honest_say(这里可能需要改)&scene=3001&buddyflag=0&srv_para=chatmsg:&text_evidence=&img_evidence=&url_evidence=&video_evidence=&file_evidence=&audio_evidence=&user_input_param=REPORT_IP=0&EVIL_IP=0&cryptograph=(密码，每次都不一样)

**Comment by RubyCos** [comment]
现在从js返回的数据来看，confessorid（或者fromEncodeuin等等）可以说没有什么价值，目前怀疑是这样的。当某个坦白说发过去时候，云端会加密ID或者产生一个序号（假如是序号可能就难破了，毕竟序号是可以随机定的，根本没有什么价值），然后发给接收的人，接收的人回复的时候也是通过这个confessorid返回到云端解密，或者配对序列然后还原QQ号码，再发给那个发坦白说的人。可以说云端的操作是完全不透明的，除非你想办法有什么漏洞搞到。可以说这腾讯用这种方法几乎没有什么漏洞了。毕竟腾讯也不想用一个加密好的密文然后给你再手机解密出那个秘密QQ号，而那个秘密QQ号完全可以在解密后的内存中拦截获取，这样的加密还有什么意义？然后我也对照了之前的办法，都是通过这样方法的。还有上面那个CSDN上的方法后面也是没用了，直接给我返回一个233334错误码，旁边还有颜文字嘲笑你，超耐磨面（cnmm）
